export { default as BarChartPage } from './chart/Bar'
export {default as CalendarPage } from './Calendar'
export { default as ContactsPage } from './Contacts'
export { default as DashboardPage } from './Dashboard'
export { default as FAQPage } from './FAQ'
export { default as FormPage } from './Form'
export { default as GeographyPage } from './Geography'
export { default as InvoicesPage } from './Invoices'
export { default as LineChartPage } from './chart/Line'
export { default as PieChartPage } from './chart/Pie'
export { default as TeamPage } from './Team'